version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - run:
          name: Install Package
          command: |
            poetry install
      - run:
          name: Tpye check App
          command: |
            poetry run mypy .
      - run:
          name: Lint App
          command: |
            black .
      - run:
          name: Test App
          command: |
            mkdir store
            poetry run pytest -v --cov=object_detection

workflows:
  main:
    jobs:
      - build-and-test
